let menuData=[];let cart=[];let currentCategory='all';
async function loadMenu(){try{const r=await fetch('/api/menu');menuData=await r.json();renderMenu('all')}catch(e){document.getElementById('menuGrid').innerHTML='<p>Menu is temporarily unavailable.</p>'}}
function renderMenu(cat='all'){currentCategory=cat;const q=(document.getElementById('menuSearch')?.value||'').trim().toLowerCase();const grid=document.getElementById('menuGrid');if(!grid)return;const list=menuData.filter(f=>(cat==='all'||f.category===cat)&&(!q||f.name.toLowerCase().includes(q)));grid.innerHTML=list.map(f=>`<article class="food-card"><div class="food-image">${f.image?`<img src="${f.image}" alt="${f.name}">`:foodEmoji(f.category)}</div><div class="food-body"><h3>${teluguName(f.name)}</h3><p>${f.description||'Fresh vegetarian preparation'}<br>${f.available&&f.stock>0?`${f.stock} available`:'Currently unavailable'}</p><div class="food-row"><span class="price">₹${f.price}</span><button class="add" ${!f.available||f.stock<1?'disabled':''} onclick="addToCart(${f.id})">${!f.available||f.stock<1?'Unavailable':'+ Add'}</button></div></div></article>`).join('')||'<p>No dishes found.</p>'}
function teluguName(n){const m={'Andhra Veg Meals':'ఆంధ్ర వెజ్ మీల్స్','Special Veg Meals':'స్పెషల్ వెజ్ మీల్స్','Paneer 65':'పనీర్ 65','Gobi 65':'గోబీ 65','Veg Biryani':'వెజ్ బిర్యానీ','Mushroom Biryani':'మష్రూమ్ బిర్యానీ','Gulab Jamun':'గులాబ్ జామున్','Payasam':'పాయసం','Idli':'ఇడ్లీ','Vada':'వడ','Dosa':'దోస','Pesarattu':'పెసరట్టు','Pulihora':'పులిహోర'};return m[n]||n}
function foodEmoji(c){return c==='biryani'?'🍚':c==='starters'?'🥗':c==='desserts'?'🍮':c==='tiffins'?'🥞':'🍛'}
function filterMenu(cat,btn){document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderMenu(cat)}
function addToCart(id,qty=1){const f=menuData.find(x=>x.id===id);if(!f)return;const item=cart.find(x=>x.id===id);if(item)item.quantity=Math.min(item.quantity+qty,f.stock);else cart.push({id:f.id,name:f.name,price:f.price,quantity:Math.min(qty,f.stock)});updateCart();openCart()}
function updateCart(){const count=cart.reduce((s,x)=>s+x.quantity,0);document.getElementById('cartCount').textContent=count;const box=document.getElementById('cartItems');if(!cart.length){box.innerHTML='<div class="cart-items" style="padding:30px;text-align:center;color:#806b5a">Your cart is empty.</div>'}else{box.innerHTML='<div class="cart-items">'+cart.map(f=>`<div class="cart-item"><div><b>${f.name}</b><div style="color:#806b5a">₹${f.price} × ${f.quantity}</div></div><div class="qty"><button onclick="changeQty(${f.id},-1)">−</button><span>${f.quantity}</span><button onclick="changeQty(${f.id},1)">+</button></div></div>`).join('')+'</div>'}document.getElementById('cartTotal').textContent='₹'+cart.reduce((s,f)=>s+f.price*f.quantity,0)}
function changeQty(id,d){const x=cart.find(i=>i.id===id);const f=menuData.find(i=>i.id===id);if(!x)return;x.quantity+=d;if(x.quantity<1)cart=cart.filter(i=>i.id!==id);else if(f)x.quantity=Math.min(x.quantity,f.stock);updateCart()}
function openCart(){updateCart();document.getElementById('cartOverlay').classList.remove('hidden')}
function closeCart(e){if(!e||e.target===e.currentTarget)document.getElementById('cartOverlay').classList.add('hidden')}
async function checkout(){if(!cart.length){alert('Add some food first.');return}const name=document.getElementById('orderName').value.trim(),phone=document.getElementById('orderPhone').value.trim(),address=document.getElementById('orderAddress').value.trim(),payment=document.querySelector('input[name="payment"]:checked')?.value;if(!name||!phone||!address){alert('Please enter name, phone and complete delivery address.');return}const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,address,payment_method:payment,items:cart.map(x=>({menu_id:x.id,quantity:x.quantity}))})});const d=await r.json();if(!r.ok){alert(d.error||'Order failed');return}localStorage.setItem('lastOrderId',d.order.id);document.getElementById('successText').innerHTML=`Order <b>#${d.order.id}</b> received.<br>Total: <b>₹${d.order.total}</b><br>Payment: <b>${payment==='cash'?'Cash on Delivery':'Online payment (demo)'}</b><br><br>You can track it below using ${phone}.`;cart=[];updateCart();document.getElementById('cartOverlay').classList.add('hidden');document.getElementById('successOverlay').classList.remove('hidden');document.getElementById('trackPhone').value=phone;loadMenu();loadCustomerOrders()}
function closeSuccess(e){if(!e||e.target===e.currentTarget)document.getElementById('successOverlay').classList.add('hidden')}
async function loadCustomerOrders(){const phone=document.getElementById('trackPhone').value.trim();if(!phone)return;const r=await fetch('/api/orders?phone='+encodeURIComponent(phone));const d=await r.json();const box=document.getElementById('customerOrders');if(!r.ok){box.innerHTML='<p>'+d.error+'</p>';return}box.innerHTML=d.length?d.map(o=>`<div class="order-summary"><div class="order-top"><b>Order #${o.id}</b><span class="order-status">${o.status.replaceAll('_',' ')}</span></div><div class="order-lines">${o.items.map(i=>`${i.name} × ${i.quantity} — ₹${i.price*i.quantity}`).join('<br>')}</div><div><b>Total ₹${o.total}</b> • ${o.payment_method==='cash'?'Cash on Delivery':'Online payment'} • ${o.payment_status}</div><div style="font-size:11px;color:#806b5a;margin-top:6px">Deliver to: ${o.address}<br>${o.created_at}</div></div>`).join(''):'<p style="color:#806b5a">No orders found for this phone number.</p>'}
async function bookTable(e){e.preventDefault();const data={date:bookDate.value,time:bookTime.value,guests:guests.value,name:bookName.value.trim(),phone:bookPhone.value.trim()};const r=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();document.getElementById('bookingResult').textContent=d.success?`✓ Confirmed! Table ${d.table_no} • Booking #${d.reservation_id} • ${d.date} ${d.time}`:(d.message||d.error)}
function openChat(){document.getElementById('chatOverlay').classList.remove('hidden');setTimeout(()=>document.getElementById('chatInput').focus(),100)}
function closeChat(e){if(!e||e.target===e.currentTarget)document.getElementById('chatOverlay').classList.add('hidden')}
function quickChat(q){document.getElementById('chatInput').value=q;sendChat({preventDefault(){}})}
function addMsg(t,type){const box=document.getElementById('chatMessages'),d=document.createElement('div');d.className='msg '+type;d.textContent=t;box.appendChild(d);box.scrollTop=box.scrollHeight}
async function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput'),q=input.value.trim();if(!q)return;addMsg(q,'user');input.value='';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});const d=await r.json();addMsg(d.reply,'bot');if(d.action==='add_to_cart'&&d.items){d.items.forEach(i=>{if(i.available)addToCart(i.menu_id,i.quantity)});document.getElementById('chatOverlay').classList.add('hidden')}}catch(_){addMsg('Assistant temporarily unavailable.','bot')}}
loadMenu();updateCart();document.addEventListener('DOMContentLoaded',()=>{const d=new Date();document.getElementById('bookDate').min=d.toISOString().slice(0,10);if(location.pathname==='/menu')setTimeout(()=>document.getElementById('menu')?.scrollIntoView(),200);const last=localStorage.getItem('lastOrderId');if(last)document.getElementById('trackPhone').placeholder='Enter phone to track Order #'+last})
